config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  devise_for :users
  resources :users

  resources :products #, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  root 'sessions#index'

end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_notices.erb
<% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>
<% if flash[:warning] %>
    <div class="alert alert-warning"><%= flash[:warning] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheHatGame</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

  <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
  <!--<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->
</head>
<body>
<!--Navbar start-->
<nav class="navbar navbar-inverse navbar-fixed-top" >
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand"> <%= link_to 'The Hat Game', root_path, class: 'navbar-brand' %>
        <img  class="logo"  src="https://s3-us-west-2.amazonaws.com/thehatgame/HatGameLogo.png">

      </a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li class="active">
           <%= link_to 'Products', products_path %>
            <span class="sr-only">(current)</span>
          </li>
        <li><%= link_to 'Home', root_path %></li>
      </ul>

    </div>
  </div>
</nav>
<!--Navbar ends-->

<%= render 'layouts/notices' %>

<div class="container">
  <div class="row">
    <!-- shopping cart use to be here....now its just a placeHolder -->
    <!--<div class="col-xs-6 text-right">-->
      <!--<h1 class="cart-text"></h1>-->
    <!--</div>-->
  </div>
  <%= yield %>
  <hr>
  <!-- Footer -->

  <footer id="footer" class="vspace20">
    <div class="container">
      <div class="row">
        <div class="span6">
          <h4>Info</h4>
          <ul class="nav nav-stacked">
            <li><a href="#">Sell Conditions</a>
            <li><a href="#">Shipping Costs</a>
            <li><a href="#">Shipping Conditions</a>
            <li><a href="#">Returns</a>
            <li><a href="#">About Us</a>
          </ul>
        </div>

        <div class="span6">
          <h4>Location and Contacts</h4>
          <p><i class="icon-map-marker"></i>&nbsp;I do not Know Avenue, A City</p>
          <p><i class="icon-phone"></i>&nbsp;Phone: 234 739.126.72</p>
          <p><i class="icon-print"></i>&nbsp;Fax: 213 123.12.090</p>
          <p><i class="icon-envelope"></i>&nbsp;Email: info@mydomain.com</p>
          <p><i class="icon-globe"></i>&nbsp;Web: http://www.mydomain.com</p>
        </div>

      </div>

    </div>
  </footer>

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p>Copyright &copy; The Hat Game 2015</p>
      </div>
    </div>
  </footer>
</div>
<div>
  <!-- Latest compiled and minified JavaScript -->
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->
</div>
</body>

</html>